class RubyTestGenerator < TestGenerator
  def generated_test_filename
    "test_#{test_case_name}.rb"
  end

  def test_class_template
    <<~TEMPLATE
      # AUTOGENERATED FILE - DO NOT EDIT
      require "helper"

      class <%= class_name %>Test < ::Minitest::Test
        attr_reader :instructions

        def setup
          @instructions = <%= instructions %>
        end
      <% tests.each do |test| %>
        def test_<%= test["name"] %>
          context = <% if test["context"].nil? %>nil<% else %><%= test["context"] %><% end %>
          expected_result = <% if test["result"].nil? %>nil<% else %><%= test["result"] %><% end %>

          e = ::Predicator::Evaluator.new instructions, context
          assert_equal expected_result, e.result
          assert_empty e.stack
        end
      <% end %>
      end
    TEMPLATE
  end
end
